env:
  es2021: true
extends:
  - plugin:svelte/recommended
  - eslint:recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  extraFileExtensions: ['.svelte']
overrides:
  - files: ['*.svelte']
    parser: 'svelte-eslint-parser'
    parserOptions:
      parser: '@typescript-eslint/parser'